use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::{AruError, IoContext, Result};

pub const STATE_FILE: &str = ".aru/state.toml";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub struct StateEntry {
    pub destination: String,
    pub kind: String,
    pub key: String,
    pub mode: String,
    pub last_applied_digest: String,
    pub lock_identity: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skill_metadata: Option<crate::skill::metadata::MetadataState>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct State {
    pub version: u32,
    #[serde(default, rename = "entry")]
    pub entries: Vec<StateEntry>,
}

impl Default for State {
    fn default() -> Self {
        Self {
            version: 1,
            entries: Vec::new(),
        }
    }
}

impl State {
    pub fn load(project: &Path) -> Result<Self> {
        let path = project.join(STATE_FILE);
        if !path.exists() {
            return Ok(Self::default());
        }
        let text = std::fs::read_to_string(&path).at(&path)?;
        let mut state: Self = toml::from_str(&text).map_err(|source| AruError::Toml {
            path: path.clone(),
            source,
        })?;
        if !matches!(state.version, 1 | 2) {
            return Err(AruError::msg(format!(
                "unsupported state version {}; expected 1 or 2",
                state.version
            )));
        }
        state.normalize();
        Ok(state)
    }

    pub fn normalize(&mut self) {
        if self
            .entries
            .iter()
            .any(|entry| entry.skill_metadata.is_some())
        {
            // Older binaries must refuse this state rather than discard overrides.
            self.version = 2;
        }
        self.entries.sort_by(|left, right| {
            (&left.kind, &left.key, &left.destination).cmp(&(
                &right.kind,
                &right.key,
                &right.destination,
            ))
        });
        self.entries.dedup_by(|left, right| {
            left.kind == right.kind
                && left.key == right.key
                && left.destination == right.destination
        });
    }

    pub fn bytes(&self) -> Result<Vec<u8>> {
        let mut state = self.clone();
        state.normalize();
        let body = toml::to_string_pretty(&state)
            .map_err(|error| AruError::msg(format!("could not serialize state: {error}")))?;
        Ok(format!("# Local deployment state generated by aru.\n{body}").into_bytes())
    }

    pub fn by_identity(&self) -> BTreeMap<(String, String, String), &StateEntry> {
        self.entries
            .iter()
            .map(|entry| {
                (
                    (
                        entry.kind.clone(),
                        entry.key.clone(),
                        entry.destination.clone(),
                    ),
                    entry,
                )
            })
            .collect()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OwnershipAction {
    Create,
    Update,
    Adopt,
    Noop,
    Remove,
    ForgetMissing,
    IgnoreUnmanaged,
}

pub fn reconcile(
    key: &str,
    current_digest: Option<&str>,
    state: Option<&StateEntry>,
    baseline_digest: Option<&str>,
    desired_digest: Option<&str>,
    force: bool,
) -> Result<OwnershipAction> {
    match desired_digest {
        Some(desired) => match (current_digest, state) {
            (None, _) => Ok(OwnershipAction::Create),
            (Some(current), Some(owned)) if current == owned.last_applied_digest => {
                if current == desired {
                    Ok(OwnershipAction::Noop)
                } else {
                    Ok(OwnershipAction::Update)
                }
            }
            (Some(current), Some(_)) => Err(AruError::msg(format!(
                "drift: aru-owned entry {key:?} was manually modified (current {current})"
            ))),
            (Some(current), None) if baseline_digest == Some(current) && current == desired => {
                Ok(OwnershipAction::Adopt)
            }
            (Some(current), None) if force => {
                let _ = current;
                Ok(OwnershipAction::Update)
            }
            (Some(_), None) => Err(AruError::msg(format!(
                "collision: unmanaged entry {key:?} already exists; inspect it or rerun with --force"
            ))),
        },
        None => match (current_digest, state) {
            (Some(current), Some(owned)) if current == owned.last_applied_digest => {
                Ok(OwnershipAction::Remove)
            }
            (Some(_), Some(_)) => Err(AruError::msg(format!(
                "drift: refusing to remove manually modified entry {key:?}"
            ))),
            (None, Some(_)) => Ok(OwnershipAction::ForgetMissing),
            (_, None) => Ok(OwnershipAction::IgnoreUnmanaged),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn state(digest: &str) -> StateEntry {
        StateEntry {
            destination: ".agents/skills/test".into(),
            kind: "skill".into(),
            key: "test".into(),
            mode: "copy".into(),
            skill_metadata: None,
            last_applied_digest: digest.into(),
            lock_identity: "lock".into(),
        }
    }

    #[test]
    fn exact_baseline_can_be_adopted_but_collision_cannot() {
        assert_eq!(
            reconcile("test", Some("a"), None, Some("a"), Some("a"), false).unwrap(),
            OwnershipAction::Adopt
        );
        assert!(reconcile("test", Some("b"), None, Some("a"), Some("a"), false).is_err());
    }

    #[test]
    fn drift_is_never_removed() {
        assert!(
            reconcile(
                "test",
                Some("manual"),
                Some(&state("old")),
                None,
                None,
                false
            )
            .is_err()
        );
    }

    #[test]
    fn v1_golden_state_round_trips_to_identical_bytes() {
        let fixture = include_str!("../tests/fixtures/contracts/state.toml");
        let state: State = toml::from_str(fixture).unwrap();
        assert_eq!(state.bytes().unwrap(), fixture.as_bytes());
    }
}
